# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: MyAgent367
  demands: npm

stages:
- stage: SonarQube
  displayName: SonarQube stage
  jobs:
  - job: SonarQubeJob
    displayName: SonarQube job
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube' 
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902' 
        cliProjectName: 'WaitOntario' 
        cliSources: 'C:\agent_work\3\s' 
    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
        
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: Build job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - script: |
        npm install
        npm test
        # Command to generate code coverage report (example)
        # npm run coverage
      displayName: 'Run unit tests and generate code coverage report'
      
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: |
           src/*
           public/*
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy project files'
    
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'npmartifact'
        targetPath: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'pipeline'
      displayName: 'Publish npm artifact'
      
- stage: Delivery
  displayName: 'Delivery Stage'
  jobs:
  - job: DeploymentJob
    displayName: 'Deployment Job'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'npmartifact'  # Name of the artifact to download
        downloadPath: '$(Build.ArtifactStagingDirectory)'  # Path to download the artifact to


      displayName: 'Deploy Artifact'
