# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Kumail367
  demands: npm

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: Build job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - script: |
        npm install
        npm test
        # Command to generate code coverage report (example)
        # npm run coverage
      displayName: 'Run unit tests and generate code coverage report'

- stage: Deliver
  displayName: Deliver stage
  jobs:
  - job: DeliverJob
    displayName: Deliver job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js for release'

    - script: |
        # Use the project's build tool to release the artifact
        # For example, if you're using npm, you might run `npm publish` here
        # Replace the command below with the actual command to release your artifact
        echo "Release artifact using build tool"
      displayName: 'Release artifact using build tool'
      
- stage: SonarQube
  displayName: SonarQube stage
  jobs:
  - job: SonarQubeJob
    displayName: SonarQube job
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube' # Name of the SonarQube service connection configured in Azure DevOps
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902' # Unique key for your project in SonarQube
        cliProjectName: 'WaitOntario' # Name of your project in SonarQube
        cliSources: 'frontend' # Adjusted to specify frontend directory as source code

    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
