trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      name: MyAgent367
      demands: npm

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend  # Change to the frontend directory
        npm install  # Install dependencies (optional)
        npm run build  # Execute build within frontend directory
      displayName: 'npm install and build'

    - script: |
        cd frontend  # Change to the frontend directory
        echo "Current directory: $(System.DefaultWorkingDirectory)"
        npm test -- --coverage
      displayName: 'Run Unit Tests and Generate Coverage Report'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage Results'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902'
        cliProjectName: 'WaitOntario'
        cliSources: '.'
      displayName: 'SonarQube Prepare'

    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
