trigger:
- main

pool:
  name: MyAgent367
  demands: npm

stages:
- stage: FrontendBuild
  displayName: 'Frontend Build Stage'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js for Frontend'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build Frontend'

- stage: BackendBuild
  displayName: 'Backend Build Stage'
  jobs:
  - job: BuildBackend
    displayName: 'Build Backend'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js for Backend'

    - script: |
        npm install
        # Add any additional build commands for backend
      displayName: 'npm install and build Backend'

- stage: SonarQube
  displayName: 'SonarQube Stage'
  jobs:
  - job: SonarQubeAnalysis
    displayName: 'SonarQube Analysis'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902'
        cliProjectName: 'WaitOntario'
        cliSources: '.'

    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
