trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      name: MyAgent367
      demands: npm

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        echo "Current directory: $(System.DefaultWorkingDirectory)"
        cd $(System.DefaultWorkingDirectory)/frontend  # Change to the frontend directory
        npm install 
        npm run build  # Execute build within frontend directory
      displayName: 'npm install and build'

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube' # Name of the SonarQube service connection configured in Azure DevOps
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902' # Unique key for your project in SonarQube
        cliProjectName: 'WaitOntario' # Name of your project in SonarQube
        cliSources: 'frontend' # Adjusted to specify frontend directory as source code

    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
