trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      name: MyAgent367
      demands: npm

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

    - script: 'npm run build'  # Use 'npm run build' as the build command
      displayName: 'Run Build'

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube' # Name of the SonarQube service connection configured in Azure DevOps
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902' # Unique key for your project in SonarQube
        cliProjectName: 'WaitOntario' # Name of your project in SonarQube
        cliSources: '.' # Path to the source code to be analyzed

    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
