trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      name: MyAgent367
      demands: npm

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(System.DefaultWorkingDirectory)  # Change to the root directory of the repository
        npm install  # Install dependencies
        npm run build  # Execute build
      displayName: 'Run Build'
      continueOnError: true  # Continue pipeline execution even if this step fails

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar_Qube' # Name of the SonarQube service connection configured in Azure DevOps
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_1647b74c02bf1c074d7c498b0e5f0c303ca72902' # Unique key for your project in SonarQube
        cliProjectName: 'WaitOntario' # Name of your project in SonarQube
        cliSources: '.' # Change to the root directory of the repository
      displayName: 'SonarQube Prepare'

    - task: SonarQubeAnalyze@4
      displayName: 'Run SonarQube analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
